version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: achievements-postgres
    hostname: ${POSTGRES_HOST}
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: achievements-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  api:
    container_name: achievements-api
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  
  worker:
    container_name: achievements-queue-worker
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - api
      - redis
    command: bash -c "pip install rq && rq worker --url redis://redis:6379"

volumes:
  postgres_data:
  redis_data: